---
- name: Dotfiles Setup
  hosts: localhost
  connection: local

  vars_prompt:
    - name: sudo_password
      prompt: "Enter sudo password (press Enter to skip)"
      private: true
      default: ""

  vars:
    ansible_become_password: "{{ sudo_password }}"

  pre_tasks:
    - name: Detect OS
      ansible.builtin.set_fact:
        is_macos: "{{ ansible_facts['os_family'] == 'Darwin' }}"
        is_linux: "{{ ansible_facts['os_family'] in ['Debian', 'RedHat'] }}"

  roles:
    ##################################
    # Package managers (OS-specific)
    ##################################
    - role: xcode
      when: is_macos
      tags: [xcode]

    - role: homebrew
      when: is_macos
      tags: [homebrew]

    - role: apt
      when: is_linux
      tags: [apt]

    ##################################
    # Common (cross-platform)
    ##################################
    - role: fonts
      tags: [fonts]

    - role: git
      tags: [git]

    - role: zsh
      tags: [zsh]

    - role: mise
      tags: [mise]

    - role: apps
      tags: [apps]

    - role: dotfiles_cli
      tags: [cli]

    ##################################
    # macOS only
    ##################################
    - role: defaults
      when: is_macos
      tags: [macos]

    - role: dock
      when: is_macos
      tags: [dock]

    ##################################
    # WSL only
    ##################################
    - role: wsl
      when: "'wsl' in group_names"
      tags: [wsl]
